FROM harbor.mobimedical.cn/base/rd-base-php:v7.4

# 安装symfony
COPY symfony /usr/local/bin/symfony
RUN chmod +x /usr/local/bin/symfony

# docker build -t harbor.mobimedical.cn/lengjing/php:v7.4 .
# docker push harbor.mobimedical.cn/lengjing/php:v7.4