version: "3"

services:
  mysql:
    image: mysql:5.7.43
    restart: always
    hostname: mysql
    container_name: mysql
    ports:
      - 33060:3306
    networks:
      - backend
    volumes:
      - $rootdir/mysql/logs:/var/log/mysql
      - $rootdir/mysql/datas:/var/lib/mysql
      - $rootdir/mysql/backups:/backups
    environment:
      MYSQL_USER: creshop
      MYSQL_PASSWORD: N4F3ABaFui
      MYSQL_ROOT_PASSWORD: RZ3X5mh8LUqkWNSh

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $rootdir/mongo/logs:/var/log/mongo
      - $rootdir/mongo/datas:/data/db
      - $rootdir/mongo/backups:/backups
    environment:
      MONGO_INITDB_USERNAME: test

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: DmO5OVFfOX
    volumes:
      - $rootdir/minio/datas:/data
    command: server /data --console-address ":9001" -address ":9000"

  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - $rootdir/redis/logs:/var/log/redis
      - $rootdir/redis/datas:/data
      - $rootdir/redis/backups:/backups

  resourcehub:
    image: harbor.mobimedical.cn/lengjing/resourcehub
    restart: always
    hostname: resourcehub
    container_name: resourcehub
    environment:
      - Env=production
    volumes:
      - $rootdir/go/logs/resourcehub:/data/www/logs

  edu2b:
    image: harbor.mobimedical.cn/lengjing/edu2b
    restart: always
    hostname: edu2b
    container_name: edu2b
    networks:
      - backend
    ports:
      - 38000:8000
    environment:
      - API_ENV=dev

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - $rootdir/www:/data/www
      - $rootdir/nginx/logs:/var/log/nginx
      - $rootdir/nginx/config/fastcgi_params:/etc/nginx/fastcgi_params
      - $rootdir/nginx/config/conf.d:/etc/nginx/conf.d
      - $rootdir/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - $rootdir/nginx/config/includes:/etc/nginx/includes

networks:
  backend:
