version: "3"

services:
  mysql:
    image: mysql:5.7.43
    restart: always
    hostname: mysql
    container_name: mysql
    ports:
      - 33060:3306
    volumes:
      - $rootdir/mysql/logs:/var/log/mysql
      - $rootdir/mysql/datas:/var/lib/mysql
      - $rootdir/mysql/backups:/backups
    environment:
      MYSQL_USER: creshop
      MYSQL_PASSWORD: N4F3ABaFui
      MYSQL_ROOT_PASSWORD: RZ3X5mh8LUqkWNSh

  edu2b:
    image: harbor.mobimedical.cn/lengjing/edu2b
    restart: always
    hostname: edu2b
    container_name: edu2b
    networks:
      - backend
    ports:
      - 38000:8000
    environment:
      - API_ENV=dev

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - $rootdir/www:/data/www
      - $rootdir/nginx/logs:/var/log/nginx
      - $rootdir/nginx/config/fastcgi_params:/etc/nginx/fastcgi_params
      - $rootdir/nginx/config/conf.d:/etc/nginx/conf.d
      - $rootdir/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - $rootdir/nginx/config/includes:/etc/nginx/includes

networks:
  backend:
